function WG_JSON(file, deployment, vehicle, repoFolder)

% ============================================================
% Wave Glider Dashboard JSON Generator
%
% Reads *.mat files from different deployments and vehicles to create
% a JSON file that can be read in by a web application to view the data.
% ============================================================


%% ------------------------------------------------------------
% Load MAT file
% ------------------------------------------------------------

data = load(file);


%% ------------------------------------------------------------
% Get vehicle data
% ------------------------------------------------------------

if ~isfield(data, vehicle)

    error( ...
        "Vehicle '%s' was not found in MAT file.", ...
        vehicle ...
    );

end

vehicleData = data.(vehicle);

if ~isfield(vehicleData, "PLD2_TAB1")

    error( ...
        "Vehicle '%s' does not contain PLD2_TAB1.", ...
        vehicle ...
    );

end

payloadData = vehicleData.PLD2_TAB1;


%% ------------------------------------------------------------
% Initialize dashboard structure
% ------------------------------------------------------------

dashboard = struct();


%% ------------------------------------------------------------
% Metadata
% ------------------------------------------------------------

dashboard.metadata.deployment = ...
    replace(string(deployment), "_", " ");

dashboard.metadata.vehicle = ...
    string(vehicle);

dashboard.metadata.generated = ...
    char( ...
        datetime( ...
            "now", ...
            "TimeZone", ...
            "UTC" ...
        ) ...
    );


%% ------------------------------------------------------------
% Required Time
% ------------------------------------------------------------

if ~isfield(payloadData, "time")

    error( ...
        "Required field 'time' was not found in PLD2_TAB1." ...
    );

end

t = datetime( ...
    payloadData.time, ...
    "ConvertFrom", ...
    "datenum", ...
    "TimeZone", ...
    "UTC" ...
);

% Convert MATLAB datenum time to Unix milliseconds.

dashboard.time = ...
    posixtime(t) * 1000;


%% ------------------------------------------------------------
% Required Position Variables
%
% Each row contains:
%
% 1. JSON field name
% 2. Preferred source field
% 3. Alternate source field
% ------------------------------------------------------------

requiredNavigation = {

    "latitude", ...
    "latitude_sitex_Avg", ...
    "latitude_Avg";

    "longitude", ...
    "longitude_sitex_Avg", ...
    "longitude_Avg"

};


for i = 1:size(requiredNavigation, 1)

    jsonName = ...
        requiredNavigation{i, 1};


    preferredField = ...
        requiredNavigation{i, 2};


    alternateField = ...
        requiredNavigation{i, 3};


    % --------------------------------------------------------
    % Preferred field:
    % latitude_sitex_Avg
    % longitude_sitex_Avg
    % --------------------------------------------------------

    if isfield(payloadData,preferredField)

        dashboard.(jsonName) = ...
            payloadData.(preferredField);


    % --------------------------------------------------------
    % Alternate field:
    % latitude_Avg
    % longitude_Avg
    % --------------------------------------------------------

    elseif isfield(payloadData,alternateField)

        dashboard.(jsonName) = ...
            payloadData.(alternateField);


    % --------------------------------------------------------
    % Neither exists
    % --------------------------------------------------------

    else

        error( ...
            "Required navigation field '%s' or '%s' was not found.", ...
            preferredField, ...
            alternateField ...
        );

    end

end

%% ------------------------------------------------------------
% Optional Navigation Variables
% ------------------------------------------------------------

optionalNavigation = {

    "heading", ...
    "heading_sitex_Avg";

    "speed", ...
    "SOG_ms_sitex_Avg"

};

for i = 1:size(optionalNavigation, 1)

    jsonName = ...
        optionalNavigation{i, 1};

    sourceField = ...
        optionalNavigation{i, 2};

    if isfield(payloadData, sourceField)

        dashboard.(jsonName) = ...
            payloadData.(sourceField);

    end

end


%% ------------------------------------------------------------
% Navigation Metadata
% ------------------------------------------------------------

dashboard.field_metadata = struct();

dashboard.field_metadata.latitude = struct( ...
    "label", "Latitude", ...
    "units", "°" ...
);

dashboard.field_metadata.longitude = struct( ...
    "label", "Longitude", ...
    "units", "°" ...
);

if isfield(dashboard, "heading")

    dashboard.field_metadata.heading = struct( ...
        "label", "Heading", ...
        "units", "°" ...
    );

end

if isfield(dashboard, "speed")

    dashboard.field_metadata.speed = struct( ...
        "label", "Speed Over Ground", ...
        "units", "m/s" ...
    );

end


%% ------------------------------------------------------------
% Initialize Payload Parameter Structures
% ------------------------------------------------------------

dashboard.parameters = struct();

dashboard.parameter_metadata = struct();


%% ------------------------------------------------------------
% Payload Parameter Definitions
%
% Columns:
%
% 1. JSON parameter name
% 2. PLD2_TAB1 source field
% 3. Display label
% 4. Units
% 5. Colorscale
% 6. cmin
% 7. cmax
% ------------------------------------------------------------

parameterDefinitions = {

    "air_temperature", ...
    "atmospheric_temperature_Avg", ...
    "Air Temperature", ...
    "°C", ...
    "Turbo", ...
    [], ...
    [];

    "relative_humidity", ...
    "relative_humidity_Avg", ...
    "Relative Humidity", ...
    "%", ...
    "Viridis", ...
    0, ...
    100;

    "atmospheric_pressure", ...
    "atmospheric_pressure_Avg", ...
    "Atmospheric Pressure", ...
    "hPa", ...
    "Turbo", ...
    [], ...
    [];

    "true_wind_speed", ...
    "TrueWindSpeed_Avg", ...
    "True Wind Speed", ...
    "m/s", ...
    "Turbo", ...
    0, ...
    [];

    "true_wind_direction", ...
    "TrueWindDirection_Avg", ...
    "True Wind Direction", ...
    "°", ...
    "HSV", ...
    0, ...
    360;

    "shortwave_radiation", ...
    "SMP21_SW_Flux_Avg", ...
    "Shortwave Radiation", ...
    "W/m²", ...
    "Turbo", ...
    0, ...
    [];

    "longwave_radiation", ...
    "SGR4_LW_Flux_Avg", ...
    "Longwave Radiation", ...
    "W/m²", ...
    "Turbo", ...
    0, ...
    [];

    "uctd_temperature", ...
    "uctd_temp_Avg", ...
    "UCTD Temperature", ...
    "°C", ...
    "Turbo", ...
    [], ...
    [];

    "uctd_salinity", ...
    "uctd_sali_Avg", ...
    "UCTD Salinity", ...
    "PSU", ...
    "Viridis", ...
    [], ...
    [];

    "uctd_density", ...
    "uctd_dens_Avg", ...
    "UCTD Density", ...
    "kg/m³", ...
    "Viridis", ...
    [], ...
    [];

    "lctd_temperature", ...
    "lctd_temp_Avg", ...
    "LCTD Temperature", ...
    "°C", ...
    "Turbo", ...
    [], ...
    [];

    "lctd_salinity", ...
    "lctd_sali_Avg", ...
    "LCTD Salinity", ...
    "PSU", ...
    "Viridis", ...
    [], ...
    [];

    "lctd_density", ...
    "lctd_dens_Avg", ...
    "LCTD Density", ...
    "kg/m³", ...
    "Viridis", ...
    [], ...
    [];

    "rbr_depth", ...
    "rbr_depth_Avg", ...
    "RBR Depth", ...
    "m", ...
    "Viridis", ...
    [], ...
    [];

    "rbr_temperature", ...
    "rbr_temp_Avg", ...
    "RBR Temperature", ...
    "°C", ...
    "Turbo", ...
    [], ...
    [];

    "rbr_salinity", ...
    "rbr_sali_Avg", ...
    "RBR Salinity", ...
    "PSU", ...
    "Viridis", ...
    [], ...
    [];

    "rbr_density", ...
    "rbr_dens_Avg", ...
    "RBR Density", ...
    "kg/m³", ...
    "Viridis", ...
    [], ...
    [];

    "significant_wave_height", ...
    "Hs_sitex_std", ...
    "Significant Wave Height", ...
    "m", ...
    "Turbo", ...
    0, ...
    [];

    "significant_wave_height", ...
    "Hs_std", ...
    "Significant Wave Height", ...
    "m", ...
    "Turbo", ...
    0, ...
    [];

};


%% ------------------------------------------------------------
% Add Available Payload Parameters
% ------------------------------------------------------------

for i = 1:size(parameterDefinitions, 1)

    jsonName = ...
        parameterDefinitions{i, 1};

    sourceField = ...
        parameterDefinitions{i, 2};

    label = ...
        parameterDefinitions{i, 3};

    units = ...
        parameterDefinitions{i, 4};

    colorscale = ...
        parameterDefinitions{i, 5};

    cmin = ...
        parameterDefinitions{i, 6};

    cmax = ...
        parameterDefinitions{i, 7};

    % Only create this parameter if it exists.

    if isfield(payloadData, sourceField)

        % Add parameter data.

        dashboard.parameters.(jsonName) = ...
            payloadData.(sourceField);

        % Add matching metadata.

        dashboard.parameter_metadata.(jsonName) = struct( ...
            "label", label, ...
            "units", units, ...
            "colorscale", colorscale, ...
            "cmin", cmin, ...
            "cmax", cmax ...
        );

        fprintf( ...
            "Added parameter: %s\n", ...
            jsonName ...
        );

    else

        fprintf( ...
            "Parameter not found, skipping: %s\n", ...
            sourceField ...
        );

    end

end


%% JSON generation

%repoFolder = "E:\1806 - Waveglider SV3\WebDashboard";
json = deployment + "_" + vehicle + "_Dashboard.json";
outputFile = fullfile(repoFolder,"data",json);

jsonText = jsonencode(dashboard);

fid = fopen(outputFile, "w");

if fid == -1

    error("Could not open output file: %s",outputFile);

end

fprintf(fid, "%s", jsonText);

fclose(fid);

fprintf("Dashboard JSON written to:\n%s\n",outputFile);


%% Push JSON to GitHub

% Git repository
cd(repoFolder);

% Add the JSON file
[status, result] = system( ...
    "git add """ + outputFile + """" ...
    );

if status ~= 0
    error("Git add failed:\n%s", result);
end


% Commit
commitMessage = ...
    "Update " + deployment + " " + vehicle + " dashboard";

[status, result] = system( ...
    "git commit -m """ + commitMessage + """" ...
    );

if status ~= 0
    error("Git commit failed:\n%s", result);
end


% Push to GitHub
[status, result] = system("git push");

if status ~= 0
    error("Git push failed:\n%s", result);
end


fprintf("\nGitHub update successful.\n");